# Generated by Django 6.0.6 on 2026-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keycloak_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
