# Generated by Django 6.0.6 on 2026-06-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('api_server_url', models.URLField(help_text='Kubernetes API server URL, e.g. https://192.168.1.10:6443')),
                ('service_account_token', models.TextField(help_text='Service account bearer token for cluster API access.')),
                ('ca_certificate', models.TextField(blank=True, help_text='Optional cluster CA certificate (PEM format).')),
                ('default_namespace', models.CharField(default='default', max_length=253)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k8s_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kubernetes cluster',
                'verbose_name_plural': 'Kubernetes clusters',
                'ordering': ['name'],
            },
        ),
    ]
