# Generated by Django 6.0.6 on 2026-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprovision',
            name='provision_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
